const { generateInvoicePdf } = require('./utils/pdfGenerator');
const path = require('path');

async function runCron() {
    console.log("Starting background invoice generation job...");

    // In a real scenario, you'd fetch data from DB and build this string
    const dummyHtml = `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: sans-serif; padding: 50px; text-align: center; }
                .card { border: 2px solid #d32f2f; padding: 20px; border-radius: 10px; }
                h1 { color: #d32f2f; }
            </style>
        </head>
        <body>
            <div class="card">
                <h1>CRON GENERATED PDF</h1>
                <p>This PDF was generated by a backend script passing a full HTML string.</p>
                <p>Generated at: ${new Date().toLocaleString()}</p>
            </div>
        </body>
        </html>
    `;

    try {
        const fileName = `Cron_Invoice_${Date.now()}.pdf`;
        const filePath = path.join(__dirname, 'invoices', fileName);

        console.log(`Generating PDF from backend template...`);
        await generateInvoicePdf(dummyHtml, filePath);

        console.log("Cron job finished successfully.");
    } catch (error) {
        console.error("Cron job failed:", error);
    }
}

runCron();
